spring:
  application:
    name: panda
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.11.166:3306/panda?characterEncoding=UTF8&autoReconnect=true&failOverReadOnly=false&rewriteBatchedStatements=true
    username: root
    password: abcd1234
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      # �z�u?��?�ړ��Ғ�?�I??
      max-wait: 60000
      # �z�u?�u���v��?�s�ꎟ??�C??���v??�I��??�ځC?�ʟ|�b
      time-between-eviction-runs-millis: 60000
      # �z�u�꘢?�ڍݒr���ŏ�����??
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
mybatis:
  type-aliases-package: com.yjgu.web.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

